type: dlvae
in_channels: 3
num_hiddens: 128
num_embeddings: 512
embedding_dim: 64
sparsity_level: 5
num_residual_blocks: 2
num_residual_hiddens: 64
commitment_cost: 0.25
decay: 0.99
perceptual_weight: 0.0
learning_rate: 3e-4
beta: 0.9
compute_fid: false
log_images_every_n_steps: 100 
omp_tolerance: 1e-7
omp_debug: false