# configs/model/vqvae.yaml
type: vqvae
in_channels: 3
num_hiddens: 128
num_embeddings: 512
embedding_dim: 64
num_residual_blocks: 2
num_residual_hiddens: 64
commitment_cost: 0.25
decay: 0.99
perceptual_weight: 0.5
compute_fid: true
log_images_every_n_steps: 100