# configs/trainer/default.yaml
learning_rate: 3e-4
beta: 0.9
max_epochs: 10
accelerator: "gpu"
devices: 2
strategy: deepspeed_stage_2
precision: 16-mixed
gradient_clip_val: 1.0
log_every_n_steps: 50
early_stopping_patience: null # Disable early stopping by default to run full max_epochs