# configs/trainer/default.yaml
learning_rate: 3e-4
beta: 0.9
max_epochs: 50
accelerator: "gpu"
devices: 2
strategy: ddp
precision: 16-mixed
gradient_clip_val: 1.0
log_every_n_steps: 50
early_stopping_patience: 10 # Number of epochs with no improvement after which training will be stopped