# configs/trainer/default.yaml
learning_rate: 1e-3
beta: 0.9
max_epochs: 1
accelerator: "gpu"
devices: 2
strategy: "ddp"
precision: 32
gradient_clip_val: 1.0
log_every_n_steps: 100
early_stopping_patience: null # Disable early stopping by default to run full max_epochs
val_check_interval: 2000
