# configs/trainer/default.yaml
learning_rate: 3e-4
beta: 0.9
max_epochs: 100
accelerator: "gpu"
devices: 2
strategy: ddp_find_unused_parameters_true
precision: 32
gradient_clip_val: 1.0
log_every_n_steps: 50
early_stopping_patience: null # Disable early stopping by default to run full max_epochs